spec:
  additionalContents: false
  contents:
    - description: Folder containing deployment files for a Docker-based service deployment
      type: folder
      name: docker
      required: true # to be adjusted when we add other deployment models
    - description: Configuration file describing variations available for deployment
      type: file
      name: "variants.yml"
      contentMediaType: "application/x-yaml"
      required: false
      $ref: "./variants.spec.yml"